apiVersion: v1
kind: Pod

metadata:
  name: securitycontext-demo

spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000

  containers:
    - name: demo
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "id; sleep 3600"]
      securityContext:
        readOnlyRootFilesystem: true
