apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "env | grep DEMO_; sleep 3600"]
          envFrom:
            - configMapRef:
                name: demo-config
